Debug: check DOTFILES and dotbot path

diff --git a/install b/install
--- a/install
+++ b/install
@@ -48,6 +48,9 @@ main() {
   # Don't use `run` here - sourcing in a pipeline loses exports
   source 'zsh/env.sh'
   set -u
+  echo "DEBUG: DOTFILES=$DOTFILES"
+  echo "DEBUG: Checking if dotbot exists at $DOTFILES/dotbot/bin/dotbot"
+  ls -la "$DOTFILES/dotbot/bin/dotbot" || echo "DEBUG: dotbot not found!"
 
   header 'Linking other needed files'
   link_files
