Make dotbot failure non-fatal

diff --git a/install b/install
--- a/install
+++ b/install
@@ -58,9 +58,15 @@ main() {
   header 'Installing dotfiles'
   # Only run dotbot if it exists (may not in CI if submodules aren't populated)
   if [ -x "$DOTFILES/dotbot/bin/dotbot" ]; then
+    set +e
     run bin/sync_dotbot
+    dotbot_status=$?
+    set -e
+    if [ $dotbot_status -ne 0 ]; then
+      echo "       Dotbot exited with status $dotbot_status, continuing anyway"
+    fi
   else
-    echo "       Skipping dotbot (not found)"
+    echo "       Skipping dotbot (not found at $DOTFILES/dotbot/bin/dotbot)"
   fi
 
   header 'Setting up Vim'
